# Nova incremental build — dependency checker
# Called per .cpp file. Reads the .d file generated by GCC -MMD -MF.
# Exit 1 = needs recompilation. Exit 0 = up to date.
#
# Inputs via environment variables (avoids quoting issues in batch):
#   NOVA_OBJ  — absolute path to the .o file
#   NOVA_DEP  — absolute path to the .d file

param()

$obj = $env:NOVA_OBJ
$dep = $env:NOVA_DEP

# .o or .d missing -> must compile
if (-not (Test-Path $obj)) { exit 1 }
if (-not (Test-Path $dep)) { exit 1 }

$t = (Get-Item $obj).LastWriteTime

# Read .d file and join continuation lines
$raw = (Get-Content $dep -Raw) -replace '\\\r?\n', ' '

# Skip the target (ends with ".o:") — works with Windows absolute paths
# e.g. "C:/path/to/file.o: C:/dep1.hpp C:/dep2.hpp ..."
$depList = ($raw -replace '^.*?\.o[^:]*:\s*', '') -split '\s+' |
           Where-Object { $_ -and $_ -ne '\' }

# If parsing failed (empty list) -> recompile to be safe
if (-not $depList) { exit 1 }

# Recompile if any dependency is newer than the .o
foreach ($f in $depList) {
    if ((Test-Path $f) -and (Get-Item $f).LastWriteTime -gt $t) {
        exit 1
    }
}

exit 0
